### PR TITLE
Po merge

### PR DESCRIPTION
**Pull request by stanislav-brabec**

### CODE REVIEW

**Comment by aschnell** [comment]
I don't like having the generated pot file included in the git repository. This just generates unneeded diffs and maybe even merge conflicts.

**Comment by stanislav-brabec** [comment]
It is needed for adding new languages to Weblate, and maybe in future for po updates. As it is not updated by the standard make, risks are low (much lower than po files, as pot files are never changed by Weblate). Please update together with po files by make merge or make update-po.

16. září 2016 17:02:34 SELČ, Arvin Schnell <notifications@github.com> napsal:
>I don't like having the generated pot file included in the git
>repository. This just generates unneeded diffs and maybe even merge
>conflicts.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openSUSE/snapper/pull/272#issuecomment-247623915

-- 
Best Regards / S pozdravem,

Stanislav Brabec
software developer

SUSE LINUX, s. r. o. e-mail: sbrabec@suse.com
Křižíkova 148/34 (Corso IIa) tel: +49 911 7405384547
186 00 Praha 8-Karlín fax: +420 284 084 001
Czech Republic http://www.suse.cz/
PGP: 830B 40D5 9E05 35D8 5E27 6FA3 717C 209F A04F CD76

**Comment by aschnell** [comment]
Hmm, that raises a question: Who is supposed to update the pot file and when?

**Comment by stanislav-brabec** [comment]
po files are updated by:
- Developers when they decide that the code is ready for translation. (Done by make merge, or make update-po in gettextize based Makefile; not called automatically.)
- Robot, if continuous translation is wanted. (Done by make merge, or make update-po in gettextize based Makefile.)

po files are updated by:
- Translators via Weblate when translation is done.
- Developers when they decide that the code is ready for translation. (Done by make merge, or make update-po in gettextize based Makefile; not called automatically.)
- Robot, if continuous translation is wanted. (Done by make merge, or make update-po in gettextize based Makefile.)

So in general, pot file is under control of developer. Its change (together with po files update) indicates that developers made the code ready for translation.

**Comment by aschnell** [comment]
For snapper I think continuous translation are wanted. Am I now force to maintain my own robot?

It is still unclear to me why the change is needed.

**Comment by aschnell** [comment]
Meanwhile the pot file is included in the git repository.

**Pull request closed without merging**
