### PR TITLE
Clean up the .spec file template

### PR DESCRIPTION
**Pull request by pjanouch**
- applied spec-cleaner
 - assumed SUSE everywhere
 - made sure libtool files aren't installed
 - split configuration into another package

### CODE REVIEW

**Comment by aschnell** [comment]
Fails at least with Fedora 23.

**Comment by pjanouch** [comment]
The current version fails as well for both Fedora 23 and 24 on OBS, and I removed the SUSE checks intentionally as advised by @scarabeusiv . RedHat/Fedora maintain their own spec file for snapper.

**Comment by aschnell** [comment]
With some research you could find that SUSE provides packages also for Fedora, see https://build.opensuse.org/project/monitor/filesystems%3Asnapper.

**Comment by pjanouch** [comment]
That is for an outdated version, though.

**Comment by aschnell** [comment]
With minor adjustments it works.

The product owner even wants to automate submission to that project (https://trello.com/c/HnurGpsR/688-3-resolve-the-double-development-project-for-snapper) so any change making the situation worse is not acceptable.

**Comment by scarabeusiv** [comment]
Ok just few points:

1) fedora does not use it and provide their own package from within their repository http://pkgs.fedoraproject.org/cgit/rpms/snapper.git/
2) that trello board is inaccesible so we can't tell you what is in there and if it make sense
3) whom is the product owner so I could talk to him? Also I still think the openSUSE developement and quality of openSUSE packages take priority over providing package to our competing distribution.

**Comment by aschnell** [comment]
Just a few remarks:

1. We also provide packages for other distributions as already mentioned. This was requested (not by fate AFAIR) by Matthias Eckermann years ago to promote snapper.

2. Sorry for that. Please talk to the product owner Jiri Srain.

3. The product owner is Jiri Srain. And finally: Portability is an important issue for software we develop at SUSE, esp. since the software is included in many distributions, and the build service project is also used to check the portability.

So please talk with the product owner before reopening.

**Pull request closed without merging**
