### PR TITLE
It'd be better to install timers.target.wants

### PR DESCRIPTION
**Pull request by henrich**
How about setting those timers as [Install] WantedBy=timers.target?

### CODE REVIEW

**Comment by NicoHood** [comment]
I've no idea if the PR is correct, but if so you should also edit the new boot timer:
https://github.com/openSUSE/snapper/blob/master/data/boot.timer

**Comment by henrich** [comment]
On Mon, 03 Oct 2016 05:25:07 -0700
Nico <notifications@github.com> wrote:
> I've no idea if the PR is correct, but if so you should also edit the new boot timer:
> https://github.com/openSUSE/snapper/blob/master/data/boot.timer

 Probably yes, I thought if my proposal is okay, then will check
 boot timer. But maybe it is okay to merge both changes.

**Comment by aschnell** [comment]
The change looks OK to me after reading https://www.freedesktop.org/software/systemd/man/systemd.special.html. Please also change boot.timer as NicoHood already mentioned.

**Comment by aschnell** [comment]
Thanks for the patch.

**Pull request merged**
